// Forza Horizon 6 - shared challenge data
var FORZA_DATA = {
    countries: [
      { id: 'de', name: 'Deutschland', code: 'DE', brands: ['BMW', 'Porsche', 'Audi', 'Mercedes-AMG', 'Volkswagen', 'Opel', 'Ruf', 'ALPINA'] },
      { id: 'jp', name: 'Japan', code: 'JP', brands: ['Nissan', 'Toyota', 'Honda', 'Mazda', 'Mitsubishi', 'Subaru', 'Lexus', 'Infiniti', 'Nissan NISMO'] },
      { id: 'us', name: 'USA', code: 'US', brands: ['Ford', 'Chevrolet', 'Dodge', 'Shelby', 'Cadillac', 'Pontiac', 'Jeep', 'Hennessey', 'SRT', 'Buick'] },
      { id: 'it', name: 'Italien', code: 'IT', brands: ['Ferrari', 'Lamborghini', 'Maserati', 'Alfa Romeo', 'Pagani', 'Lancia', 'Fiat', 'Abarth'] },
      { id: 'gb', name: 'UK', code: 'GB', brands: ['Aston Martin', 'McLaren', 'Jaguar', 'Lotus', 'Bentley', 'TVR', 'BAC', 'Mini', 'Caterham', 'Noble'] },
      { id: 'fr', name: 'Frankreich', code: 'FR', brands: ['Bugatti', 'Alpine', 'Renault', 'Peugeot', 'DS Automobiles'] },
      { id: 'se', name: 'Schweden', code: 'SE', brands: ['Koenigsegg', 'Volvo', 'Polestar'] },
      { id: 'sk', name: 'Suedkorea', code: 'KR', brands: ['Hyundai', 'Kia'] },
      { id: 'au', name: 'Australien', code: 'AU', brands: ['Holden', 'HSV'] },
      { id: 'at', name: 'Oesterreich', code: 'AT', brands: ['KTM'] }
    ],

    classes: [
      { name: 'D-Klasse', code: 'D', min: 100, max: 400 },
      { name: 'C-Klasse', code: 'C', min: 401, max: 500 },
      { name: 'B-Klasse', code: 'B', min: 501, max: 600 },
      { name: 'A-Klasse', code: 'A', min: 601, max: 700 },
      { name: 'S1-Klasse', code: 'S1', min: 701, max: 800 },
      { name: 'S2-Klasse', code: 'S2', min: 801, max: 900 },
      { name: 'R-Klasse', code: 'R', min: 901, max: 998 },
      { name: 'X-Klasse', code: 'X', min: 999, max: 999 }
    ],

    drivetrains: [
      { name: 'RWD', full: 'Heckantrieb', desc: 'Nur Hinterachse' },
      { name: 'AWD', full: 'Allradantrieb', desc: 'Alle 4 Raeder' },
      { name: 'FWD', full: 'Frontantrieb', desc: 'Nur Vorderachse' },
      { name: 'SERIE', full: 'Originalantrieb', desc: 'Kein Antriebs-Swap' }
    ],

    tuningRules: [
      { title: 'Stock Motor Pflicht', desc: 'Kein Motor-Swap erlaubt, Original-Motor tunen' },
      { title: 'Keine Aero-Teile', desc: 'Keine Spoiler, Frontsplitter oder Diffusoren' },
      { title: 'Sauger-Tuning Only', desc: 'Keine Turbolader oder Kompressoren' },
      { title: 'Sleeper Optics', desc: 'Serienoptik & Serienfelgen Pflicht' },
      { title: 'Maximaler Ladedruck', desc: 'Turbo oder Kompressor hoechster Stufe Pflicht' },
      { title: 'Offroad-Profil Pflicht', desc: 'Gelaendereifen und erhoehtes Fahrwerk' },
      { title: 'Drift-Fahrwerk Pflicht', desc: 'Fahrwerk muss auf Drift abgestimmt werden' },
      { title: 'Budget Limit: 50.000 CR', desc: 'Autopreis laut Automesse max. 50.000 CR' },
      { title: 'Budget Limit: 100.000 CR', desc: 'Autopreis laut Automesse max. 100.000 CR' },
      { title: 'Manuelle Schaltung', desc: 'Nur manuelle Gangschaltung erlaubt' },
      { title: 'Gewicht > 1.500 kg', desc: 'Gewichtsreduzierung nicht unter 1.500 kg' },
      { title: 'Leichtbau < 1.200 kg', desc: 'Auto muss unter 1.200 kg gebracht werden' },
      { title: 'Nur Downgrade', desc: 'Nur Leistung reduzieren, kein Upgrade erlaubt' },
      { title: 'Swap Pflicht', desc: 'Motor-Swap ist Pflicht, kein Originalmotor' },
      { title: 'Maximale Breite', desc: 'Breiteste Karosserie-Option muss verbaut werden' },
      { title: 'Freies Tuning', desc: 'Keine zusaetzlichen Tuning-Beschraenkungen' }
    ],

    eras: [
      { name: 'Klassiker (Vor 1980)', code: '<1980' },
      { name: 'Retro (80er & 90er)', code: '80s/90s' },
      { name: 'Modern Classic (2000-2012)', code: '2000s' },
      { name: 'Modern Performance (2013-2020)', code: '2010s' },
      { name: 'Next-Gen (2021+)', code: '2021+' }
    ],

    weatherConditions: [
      { name: 'Sonnig / Trocken', desc: 'Klare Bedingungen, trockene Fahrbahn' },
      { name: 'Leichter Regen', desc: 'Nasse Fahrbahn, leicht reduzierter Grip' },
      { name: 'Starkregen', desc: 'Aquaplaning-Gefahr, deutlich weniger Grip' },
      { name: 'Nacht', desc: 'Nachtrennen, eingeschraenkte Sicht' },
      { name: 'Nacht + Regen', desc: 'Dunkelheit und nasse Fahrbahn kombiniert' },
      { name: 'Sturm', desc: 'Starkregen, Wind und schlechte Sicht' },
      { name: 'Nebel', desc: 'Sichtweite stark eingeschraenkt' },
      { name: 'Schnee / Eis', desc: 'Winterliche Bedingungen, Eis auf der Strecke' }
    ],

    tireCompounds: [
      { name: 'Strassenreifen', desc: 'Standard Strassenreifen Pflicht' },
      { name: 'Sportreifen', desc: 'Sport-Compound Pflicht' },
      { name: 'Rennreifen / Slicks', desc: 'Rennslicks Pflicht' },
      { name: 'Rally-Reifen', desc: 'Offroad/Rally-Reifen Pflicht' },
      { name: 'Drag-Reifen', desc: 'Drag-Slicks hinten Pflicht' },
      { name: 'Winterreifen', desc: 'Winterreifen oder Snow-Compound' },
      { name: 'Serienreifen', desc: 'Original-Reifentyp, kein Wechsel erlaubt' },
      { name: 'Freie Wahl', desc: 'Reifentyp frei waehlbar' }
    ],

    assistRules: [
      { name: 'Keine Assists', desc: 'ABS, TCS und Stabilitaetskontrolle aus' },
      { name: 'Nur ABS', desc: 'Nur ABS erlaubt, TCS und Stabi aus' },
      { name: 'Cockpit-Pflicht', desc: 'Nur Cockpit- oder Stossstangen-Ansicht' },
      { name: 'Kein Rueckspulen', desc: 'Rueckspulen komplett deaktiviert' },
      { name: 'Simulation-Lenkung', desc: 'Simulation-Modus fuer Lenkung Pflicht' },
      { name: 'Nur Bremslinie', desc: 'Einziger Assist: Bremslinie erlaubt' },
      { name: 'Freie Assists', desc: 'Alle Assists frei waehlbar' }
    ],

    // Disziplin-Typen — typeLabel muss den Event-Typen in FH6_OFFICIAL_EVENTS entsprechen
    disciplines: [
      { id: 'street',       name: 'Street Race',              typeLabel: 'Street',       hint: 'Waehlt ein Street-Race auf der Map' },
      { id: 'track',        name: 'Track Race',               typeLabel: 'Track',        hint: 'Waehlt ein Track-/Rundstrecken-Event auf der Map' },
      { id: 'touge',        name: 'Touge',                    typeLabel: 'Touge',        hint: 'Waehlt ein Touge-Duell auf der Map' },
      { id: 'drag',         name: 'Drag Race',                typeLabel: 'Drag Race',    hint: 'Sucht euch eine Drag Strip / Landebahn auf der Map' },
      { id: 'dirt',         name: 'Dirt / Rallye',            typeLabel: 'Dirt',         hint: 'Waehlt ein Dirt-/Schotterrennen auf der Map' },
      { id: 'crosscountry', name: 'Cross Country',            typeLabel: 'Crosscountry', hint: 'Waehlt ein Cross-Country-Event auf der Map' },
      { id: 'drift',        name: 'Driftzone',                typeLabel: 'Driftzone',    hint: 'Sucht eine Driftzone auf der Map' },
      { id: 'jump',         name: 'Jump / Gefahrenschild',    typeLabel: 'Jump',         hint: 'Sucht ein Gefahrenschild / Jump auf der Map' },
      { id: 'speedtrap',    name: 'Speed Trap / Blitzer',     typeLabel: 'Speedtrap',    hint: 'Sucht einen Speed Trap / Blitzer auf der Map' },
      { id: 'trailblazer',  name: 'Trailblazer',              typeLabel: 'Trailblazer',  hint: 'Sucht einen Trailblazer auf der Map' },
      { id: 'speedzone',    name: 'Speed Zone',               typeLabel: 'Speedzone',    hint: 'Sucht eine Speed Zone auf der Map' }
    ],

    // Player accent colors
    playerColors: [
      '#3b82f6', '#10b981', '#f59e0b', '#a855f7',
      '#ec4899', '#06b6d4', '#f97316', '#6366f1'
    ],

    // Mode descriptions
    modeDescriptions: {
      group: 'Alle Spieler: gleiches Land, gleiche Regeln.',
      individual: 'Jeder bekommt ein anderes Land, aber gleiche PI & Regeln. Fair!',
      escalation: 'PI startet niedrig und steigt pro Runde. Gleiches Auto upgraden!',
      chaos: 'Jeder Spieler bekommt komplett andere Regeln. Maximales Chaos!'
    }
  };

var FH6_OFFICIAL_EVENTS = [
    // Street Races
    { name: 'Cedar Run Street Race', mapRegion: 'Discover Japan / Hokubu', type: 'Street' },
    { name: 'Daikoku Chase Street Race', mapRegion: 'Discover Japan / Yokohama-Docks', type: 'Street' },
    { name: 'Festival Chase Street Race', mapRegion: 'Discover Japan / Festival-Umfeld', type: 'Street' },
    { name: 'Hokubu Ascent Street Race', mapRegion: 'Discover Japan / Hokubu', type: 'Street' },
    { name: 'Kita Ine Street Race', mapRegion: 'Discover Japan / Ine Kueste', type: 'Street' },
    { name: 'Matsumi Climb Street Race', mapRegion: 'Discover Japan / Matsumi', type: 'Street' },
    { name: 'Minami Chase Street Race', mapRegion: 'Discover Japan / Minamino', type: 'Street' },
    { name: 'Nachi Run Street Race', mapRegion: 'Discover Japan / Nachi', type: 'Street' },
    { name: 'Norikura Descent Street Race', mapRegion: 'Discover Japan / Sotoyama', type: 'Street' },
    { name: 'Okishinaimura Run Street Race', mapRegion: 'Discover Japan / Laendliche Region', type: 'Street' },
    { name: 'Rainbow Bridge Descent Street Race', mapRegion: 'Discover Japan / Tokio-Sued', type: 'Street' },
    { name: 'River Descent Street Race', mapRegion: 'Discover Japan / Flussdelta', type: 'Street' },
    { name: 'Shimanoyama Charge Street Race', mapRegion: 'Discover Japan / Shimanoyama', type: 'Street' },
    { name: 'Sunflower Charge Street Race', mapRegion: 'Discover Japan / Ito Region', type: 'Street' },
    { name: 'Tokyo City Docks Charge Street Race', mapRegion: 'Discover Japan / Hafen Tokio', type: 'Street' },

    // Road Races
    { name: 'Coastline Sprint', mapRegion: 'Horizon Festival / Kuestenstrasse', type: 'Track' },
    { name: 'Daikoku Circuit', mapRegion: 'Horizon Festival / Daikoku', type: 'Track' },
    { name: 'Electric Town Circuit', mapRegion: 'Horizon Festival / Tokio Akihabara', type: 'Track' },
    { name: 'Festival Sprint', mapRegion: 'Horizon Festival / Hauptgelaende', type: 'Track' },
    { name: 'Highway Circuit', mapRegion: 'Horizon Festival / Autobahn-Ring', type: 'Track' },
    { name: 'Hokubu Circuit', mapRegion: 'Horizon Festival / Hokubu', type: 'Track' },
    { name: 'Irokawa Circuit Road Race', mapRegion: 'Horizon Festival / Nangan', type: 'Track' },
    { name: 'Ito Sprint', mapRegion: 'Horizon Festival / Ito', type: 'Track' },
    { name: 'Legend Island Circuit', mapRegion: 'Horizon Festival / Legend Island', type: 'Track' },
    { name: 'Narai-Juku Circuit', mapRegion: 'Horizon Festival / Historisches Dorf', type: 'Track' },
    { name: 'Satta Sprint', mapRegion: 'Horizon Festival / Satta Pass', type: 'Track' },
    { name: 'Seaside Park Sprint', mapRegion: 'Horizon Festival / Kuestenpark', type: 'Track' },
    { name: 'Shikisai Sprint', mapRegion: 'Horizon Festival / Blumenfelder', type: 'Track' },
    { name: 'Shimanoyama Circuit', mapRegion: 'Horizon Festival / Shimanoyama', type: 'Track' },
    { name: 'Shimanoyama Sprint', mapRegion: 'Horizon Festival / Shimanoyama', type: 'Track' },
    { name: 'Shirakawa Circuit', mapRegion: 'Horizon Festival / Shirakawa-go', type: 'Track' },
    { name: 'Tateyama Kurobe Sprint', mapRegion: 'Horizon Festival / Alpenregion', type: 'Track' },
    { name: 'The Colossus', mapRegion: 'Horizon Festival / Karteuebergreifend', type: 'Track' },
    { name: 'The Goliath', mapRegion: 'Horizon Festival / Karteuebergreifend', type: 'Track' },
    { name: 'Venus Sprint', mapRegion: 'Horizon Festival / Venus Line', type: 'Track' },

    // Touge Races
    { name: 'Arashiyama Takao Touge Race', mapRegion: 'Arashiyama / Takao', type: 'Touge' },
    { name: 'Bandai Azuma Touge Race', mapRegion: 'Shimanoyama / Bandai Azuma', type: 'Touge' },
    { name: 'Hakone Nanamagari Touge Race', mapRegion: 'Nangan / Hakone-Pass', type: 'Touge' },
    { name: 'Mt. Haruna Touge Race', mapRegion: 'Takashiro / Mt. Haruna', type: 'Touge' },
    { name: 'Norikura Skyline Touge Race', mapRegion: 'Sotoyama / Norikura', type: 'Touge' },

    // Drag Strips
    { name: 'Horizon Festival Drag Strip', mapRegion: 'Horizon Festival Hauptgelaende', type: 'Drag Race' },
    { name: 'Irokawa Space Center Drag Strip', mapRegion: 'Nangan / Space Center', type: 'Drag Race' },
    { name: 'Ito Airfield Drag Strip', mapRegion: 'Ito / Flugplatz', type: 'Drag Race' },

    // Dirt Races
    { name: 'Airfield Trail', mapRegion: 'Horizon Festival / Ito', type: 'Dirt' },
    { name: 'Bamboo Forest Scramble', mapRegion: 'Horizon Festival / Bambuswald', type: 'Dirt' },
    { name: 'Cherry Field Trail', mapRegion: 'Horizon Festival / Kirschbluetenregion', type: 'Dirt' },
    { name: 'Chiheisen Scramble', mapRegion: 'Horizon Festival / Chiheisen', type: 'Dirt' },
    { name: 'Hirosaki Scramble', mapRegion: 'Horizon Festival / Hirosaki', type: 'Dirt' },
    { name: 'Hokubu Trail', mapRegion: 'Horizon Festival / Hokubu', type: 'Dirt' },
    { name: 'Horizon Stadium Scramble', mapRegion: 'Horizon Festival / Stadion', type: 'Dirt' },
    { name: 'Ine Scramble', mapRegion: 'Horizon Festival / Ine Kueste', type: 'Dirt' },
    { name: 'Ito Trail', mapRegion: 'Horizon Festival / Ito', type: 'Dirt' },
    { name: 'Kawazu Nanadaru Scramble', mapRegion: 'Horizon Festival / Nangan Loop', type: 'Dirt' },
    { name: 'Kinkaku-ji Trail', mapRegion: 'Horizon Festival / Tempelregion', type: 'Dirt' },
    { name: 'Legend Island Trail', mapRegion: 'Horizon Festival / Legend Island', type: 'Dirt' },
    { name: 'Nukabira Trail', mapRegion: 'Horizon Festival / Sotoyama', type: 'Dirt' },
    { name: 'Oyashirazu Trail', mapRegion: 'Horizon Festival / Kuestenklippen', type: 'Dirt' },
    { name: 'Sekibe Scramble', mapRegion: 'Horizon Festival / Sekibe', type: 'Dirt' },
    { name: 'Sotoyama Scramble', mapRegion: 'Horizon Festival / Sotoyama', type: 'Dirt' },
    { name: 'Sunflower Scramble', mapRegion: 'Horizon Festival / Ito', type: 'Dirt' },
    { name: 'Taiyaki Scramble', mapRegion: 'Horizon Festival / Taiyaki', type: 'Dirt' },
    { name: 'Takashiro Trail', mapRegion: 'Horizon Festival / Takashiro', type: 'Dirt' },
    { name: 'The Gauntlet', mapRegion: 'Horizon Festival / Karteuebergreifend', type: 'Dirt' },

    // Cross Country Races
    { name: 'City Docks Cross Country Circuit', mapRegion: 'Horizon Festival / Hafen Tokio', type: 'Crosscountry' },
    { name: 'Edogawa Cross Country Circuit', mapRegion: 'Horizon Festival / Edogawa', type: 'Crosscountry' },
    { name: 'Izu Cross Country', mapRegion: 'Horizon Festival / Izu-Halbinsel', type: 'Crosscountry' },
    { name: 'Legend Island Cross Country Circuit', mapRegion: 'Horizon Festival / Legend Island', type: 'Crosscountry' },
    { name: 'Nangan Cross Country Circuit', mapRegion: 'Horizon Festival / Nangan', type: 'Crosscountry' },
    { name: 'Naruo Cross Country Circuit', mapRegion: 'Horizon Festival / Naruo', type: 'Crosscountry' },
    { name: 'Oka Cross Country Circuit', mapRegion: 'Horizon Festival / Oka Huegel', type: 'Crosscountry' },
    { name: 'Ruriko-ji Cross Country', mapRegion: 'Horizon Festival / Tempelpark', type: 'Crosscountry' },
    { name: 'Shimanoyama Cross Country', mapRegion: 'Horizon Festival / Shimanoyama', type: 'Crosscountry' },
    { name: 'Shinjuku Gyoen Cross Country', mapRegion: 'Horizon Festival / Park Shinjuku', type: 'Crosscountry' },
    { name: 'Snow Forest Cross Country Circuit', mapRegion: 'Horizon Festival / Sotoyama Schnee', type: 'Crosscountry' },
    { name: 'Soni Highlands Cross Country', mapRegion: 'Horizon Festival / Soni-Ebene', type: 'Crosscountry' },
    { name: 'Takashiro Cross Country', mapRegion: 'Horizon Festival / Takashiro', type: 'Crosscountry' },
    { name: 'Tateyama Alpine Cross Country', mapRegion: 'Horizon Festival / Tateyama', type: 'Crosscountry' },
    { name: 'Temple Cross Country', mapRegion: 'Horizon Festival / Tempel-Areal', type: 'Crosscountry' },
    { name: 'The Titan', mapRegion: 'Horizon Festival / Gelaendeweit', type: 'Crosscountry' },
    { name: 'Wind Farm Cross Country', mapRegion: 'Horizon Festival / Windpark', type: 'Crosscountry' },
    { name: 'Yahikoyama Cross Country', mapRegion: 'Horizon Festival / Yahiko Berg', type: 'Crosscountry' },

    // Driftzones
    { name: 'Bandai Azuma Skyline', mapRegion: 'Shimanoyama', type: 'Driftzone' },
    { name: 'Inner City Run', mapRegion: 'Tokio City', type: 'Driftzone' },
    { name: 'Kawazu Nanadaru Loop Bridge', mapRegion: 'Nangan', type: 'Driftzone' },
    { name: 'Red Road', mapRegion: 'Shimanoyama', type: 'Driftzone' },
    { name: 'Minamino Horseshoe', mapRegion: 'Minamino', type: 'Driftzone' },
    { name: 'Nukabira Turn', mapRegion: 'Sotoyama', type: 'Driftzone' },
    { name: 'Shiro Switch', mapRegion: 'Sotoyama', type: 'Driftzone' },
    { name: 'Thunderbird', mapRegion: 'Takashiro', type: 'Driftzone' },
    { name: 'Cedar Grove', mapRegion: 'Hokubu', type: 'Driftzone' },
    { name: 'Hakone Nanamagari', mapRegion: 'Nangan', type: 'Driftzone' },
    { name: 'Seaside Trail', mapRegion: 'Ito', type: 'Driftzone' },
    { name: 'Shirakawa Curves', mapRegion: 'Minamino', type: 'Driftzone' },
    { name: 'Turbine Trail', mapRegion: 'Ito', type: 'Driftzone' },
    { name: 'Mt. Haruna', mapRegion: 'Takashiro', type: 'Driftzone' },
    { name: 'Hairpin', mapRegion: 'Shimanoyama', type: 'Driftzone' },
    { name: 'River Run', mapRegion: 'Ohtani', type: 'Driftzone' },
    { name: 'Kodachi Run', mapRegion: 'Ito', type: 'Driftzone' },
    { name: 'Tokyo City Docks', mapRegion: 'Tokio City', type: 'Driftzone' },
    { name: 'Sunflower Fields', mapRegion: 'Ito', type: 'Driftzone' },
    { name: 'Meoto Iwa Turn', mapRegion: 'Ito', type: 'Driftzone' },
    
    // Jumps
    { name: 'Festival Leap', mapRegion: 'Ohtani', type: 'Jump' },
    { name: 'Mt. Fuji View', mapRegion: 'Ohtani', type: 'Jump' },
    { name: 'Rollercoaster Leap', mapRegion: 'Minamino', type: 'Jump' },
    { name: 'Stadium Jump', mapRegion: 'Shimanoyama', type: 'Jump' },
    { name: 'Highway Jump', mapRegion: 'Shimanoyama', type: 'Jump' },
    { name: 'Clifftop Crest', mapRegion: 'Sotoyama', type: 'Jump' },
    { name: 'Alpine Heights', mapRegion: 'Sotoyama', type: 'Jump' },
    { name: 'Highlands', mapRegion: 'Takashiro', type: 'Jump' },
    { name: 'Circuit Leap', mapRegion: 'Hokubu', type: 'Jump' },
    { name: 'Airfield Take-Off', mapRegion: 'Ito Airfield', type: 'Jump' },
    { name: 'Seaside Heights', mapRegion: 'Ito', type: 'Jump' },
    { name: 'Tanbo Launch', mapRegion: 'Ito', type: 'Jump' },
    { name: 'Shirakawa-go', mapRegion: 'Minamino', type: 'Jump' },
    { name: 'Azure Drive', mapRegion: 'Ito', type: 'Jump' },
    { name: 'Farmland Falls', mapRegion: 'Takashiro', type: 'Jump' },
    { name: 'Irokawa Launch', mapRegion: 'Nangan', type: 'Jump' },
    { name: 'Nangan Heights', mapRegion: 'Nangan', type: 'Jump' },
    { name: 'Tokyo City Lookout', mapRegion: 'Shimanoyama', type: 'Jump' },
    { name: 'Tokyo City Dockside', mapRegion: 'Tokio City', type: 'Jump' },
    { name: 'Railway Bridge', mapRegion: 'Hokubu', type: 'Jump' },

    // Speedtraps
    { name: 'River Split', mapRegion: 'Minamino', type: 'Speedtrap' },
    { name: 'Lakeside Valley', mapRegion: 'Shimanoyama', type: 'Speedtrap' },
    { name: 'Rainbow Run', mapRegion: 'Tokyo City', type: 'Speedtrap' },
    { name: 'Ito Straight', mapRegion: 'Ito', type: 'Speedtrap' },
    { name: 'Tokyo City Run-Up', mapRegion: 'Ohtani', type: 'Speedtrap' },
    { name: 'Festival Line', mapRegion: 'Ohtani', type: 'Speedtrap' },
    { name: 'Flower Run', mapRegion: 'Hokubu', type: 'Speedtrap' },
    { name: 'Crossover', mapRegion: 'Takashiro', type: 'Speedtrap' },
    { name: 'Hirosaki Castle', mapRegion: 'Takashiro', type: 'Speedtrap' },
    { name: 'Highland Road', mapRegion: 'Takashiro', type: 'Speedtrap' },
    { name: 'Takashiro Bridge', mapRegion: 'Takashiro', type: 'Speedtrap' },
    { name: 'Irabu Ohashi Bridge', mapRegion: 'Hokubu', type: 'Speedtrap' },
    { name: 'Shirakawa-go Straight', mapRegion: 'Minamino', type: 'Speedtrap' },
    { name: 'Akihabara Straight', mapRegion: 'Tokyo City', type: 'Speedtrap' },
    { name: 'Nangan Turn', mapRegion: 'Nangan', type: 'Speedtrap' },
    { name: 'Lake View', mapRegion: 'Shimanoyama', type: 'Speedtrap' },
    { name: 'Airfield Runway', mapRegion: 'Ito', type: 'Speedtrap' },
    { name: 'Ine Beach', mapRegion: 'Ito', type: 'Speedtrap' },
    { name: 'Bamboo Hilltop', mapRegion: 'Hokubu', type: 'Speedtrap' },
    { name: 'Crop Fields', mapRegion: 'Takashiro', type: 'Speedtrap' },
    { name: 'Daikoku Parking Area', mapRegion: 'Tokyo City', type: 'Speedtrap' },
    { name: 'Jodogahama Grove', mapRegion: 'Nagan', type: 'Speedtrap' },
    { name: 'Izu Skyline', mapRegion: 'Nagan', type: 'Speedtrap' },
    { name: 'Stadium Back Road', mapRegion: 'Shimanoyama', type: 'Speedtrap' },
    { name: 'Main Street', mapRegion: 'Shimanoyama', type: 'Speedtrap' },
    { name: 'Riverside', mapRegion: 'Ohtani', type: 'Speedtrap' },
    { name: 'Cedar Woodland', mapRegion: 'Minamino', type: 'Speedtrap' },
    { name: 'Shibuya Crossing', mapRegion: 'Tokyo City', type: 'Speedtrap' },
    { name: 'Snowbank', mapRegion: 'Sotoyama', type: 'Speedtrap' },
    { name: 'Island Road', mapRegion: 'Legend Island', type: 'Speedtrap' },

    // Trailblazer
    { name: 'Bridge Underpasses', mapRegion: 'Ohtani', type: 'Trailblazer' },
    { name: 'Kodachi Descent', mapRegion: 'Shimanoyama', type: 'Trailblazer' },
    { name: 'Nachi Falls', mapRegion: 'Sotoyama', type: 'Trailblazer' },
    { name: 'Mountain Descent', mapRegion: 'Takashiro', type: 'Trailblazer' },
    { name: 'Forest Cut-Through', mapRegion: 'Hokubu', type: 'Trailblazer' },
    { name: 'Coastal Descent', mapRegion: 'Nangan', type: 'Trailblazer' },
    { name: 'Ropeway Run', mapRegion: 'Ito', type: 'Trailblazer' },
    { name: 'Kudarizaka', mapRegion: 'Ohtani', type: 'Trailblazer' },
    { name: 'On Par', mapRegion: 'Minamino', type: 'Trailblazer' },
    { name: 'Sekibe Kaijo', mapRegion: 'Ito', type: 'Trailblazer' },
    { name: 'Horizon Kaido', mapRegion: 'Sotoyama', type: 'Trailblazer' },

    //Speedzone
    { name: 'Highway View', mapRegion: 'Ito', type: 'Speedzone' },
    { name: 'Festival Loop', mapRegion: 'Ohtani', type: 'Speedzone' },
    { name: 'Pylons', mapRegion: 'Ohtani', type: 'Speedzone' },
    { name: 'Yahikoyama Curve', mapRegion: 'Ito', type: 'Speedzone' },
    { name: 'Fuji Shibazakura', mapRegion: 'Shimanoyama', type: 'Speedzone' },
    { name: 'Mountain Pass', mapRegion: 'Shimanoyama', type: 'Speedzone' },
    { name: 'Kōzokudō', mapRegion: 'Hokubu', type: 'Speedzone' },
    { name: 'Temple Run-Up', mapRegion: 'Takashiro', type: 'Speedzone' },
    { name: 'Snow Slopes', mapRegion: 'Sotoyama', type: 'Speedzone' },
    { name: 'Tateyama Kurobe Alpine Route', mapRegion: 'Sotoyama', type: 'Speedzone' },
    { name: 'Hirosaki Tangle', mapRegion: 'Takashiro', type: 'Speedzone' },
    { name: 'Tea Farm', mapRegion: 'Takashiro', type: 'Speedzone' },
    { name: 'Okishinaimura', mapRegion: 'Hokubu', type: 'Speedzone' },
    { name: 'Yama Trail', mapRegion: 'Ohtani', type: 'Speedzone' },
    { name: 'Farmland Curve', mapRegion: 'Minamino', type: 'Speedzone' },
    { name: 'Ocean Highway', mapRegion: 'Tokyo City', type: 'Speedzone' },
    { name: 'Seaside Park', mapRegion: 'Ito', type: 'Speedzone' },
    { name: 'Hanado', mapRegion: 'Minamino', type: 'Speedzone' },
    { name: 'Arashiyama Run', mapRegion: 'Ito', type: 'Speedzone' },
    { name: 'Minamino Curve', mapRegion: 'Minamino', type: 'Speedzone' },
    { name: 'Tall Trees', mapRegion: 'Hokubu', type: 'Speedzone' },
    { name: 'Deep Forest', mapRegion: 'Takashiro', type: 'Speedzone' },
    { name: 'Hakone Turns', mapRegion: 'Nangan', type: 'Speedzone' },
    { name: 'Matsumi Curve', mapRegion: 'Ohtani', type: 'Speedzone' },
    { name: 'Airfield Grove', mapRegion: 'Ito', type: 'Speedzone' },
    { name: 'Forest Straight', mapRegion: 'Ito', type: 'Speedzone' },
    { name: 'City Sights', mapRegion: 'Tokyo City', type: 'Speedzone' },
    { name: 'Underground Tunnel', mapRegion: 'Tokyo City', type: 'Speedzone' },
    { name: 'Ine Backstreet', mapRegion: 'Ito', type: 'Speedzone' },
    { name: 'Coastal Cliffside', mapRegion: 'Legend Island', type: 'Speedzone' }

  ];
